/* eslint-disable import/prefer-default-export */
export const ProjectActionTypes = {
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  SET_PROJECT_ERROR_MESSAGE: 'SET_PROJECT_ERROR_MESSAGE',
  SET_PROJECT_SUCCESS_MESSAGE: 'SET_PROJECT_SUCCESS_MESSAGE',
  DELETE_PROJECT_ERROR_MESSAGE: 'DELETE_PROJECT_ERROR_MESSAGE',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  INITIALIZE_PROJECTS: 'INITIALIZE_PROJECTS',
};
